#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

RobertLemke:
  Plugin:
    Blog:
      notifications:
        to:
          email: ''
          name: 'Blog Admin'
